# Generated by Django 5.2 on 2025-11-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradevalue",
            name="description",
            field=models.CharField(default="IP - In Progress", max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="historicalgradevalue",
            name="description",
            field=models.CharField(default="IP - In Progress", max_length=60, null=True),
        ),
    ]
