# Generated by Django 5.2 on 2025-12-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transcriptrequeststatus",
            options={"verbose_name_plural": "Transcript Request Status"},
        ),
    ]
