services:
  web:
    build:
      context: .
      args:
        ENV: prod
    volumes:
      - .:/code
    env_file:
      - .env-prod
    expose:
      - 8000
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

