x-default-env: &default-env
  env_file:
    - .env-pg
services:
  db:
    image: postgres:16
    container_name: tusis-dev-db
    <<: *default-env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - tusis_pgdata:/var/lib/postgresql/data
    shm_size: "64mb"
    command: >
      postgres
      -c max_connections=30
      -c shared_buffers=64MB
      -c work_mem=2MB
      -c maintenance_work_mem=32MB
      -c effective_cache_size=256MB

volumes:
  tusis_pgdata:
