services:
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-dev

  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/code
    env_file:
      - .env-dev
    depends_on:
      - db
    expose:
      - 8000

  nginx:
    image: nginx:1.22
    ports:
      - "443:443"
    volumes:
      - ./static:/static:ro
      - ./media:/media:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/selfsigned.crt:/etc/nginx/selfsigned.crt:ro
      - ./nginx/selfsigned.key:/etc/nginx/selfsigned.key:ro   
    depends_on:
      - web
      
volumes:
  postgres_data:
