FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
      graphviz \
      libglib2.0-0 \
      libpango-1.0-0 \
      libpangoft2-1.0-0 \
      libpangocairo-1.0-0 \
      libharfbuzz0b \
      libharfbuzz-subset0 \
      libcairo2 \
      libffi8 \
      libjpeg62-turbo \
      libpng16-16 \
      libxml2 \
      libxslt1.1 \
      fontconfig \
      fonts-dejavu-core \
      qrencode \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /code

COPY requirements*.txt /code/

RUN pip install --no-cache-dir -r requirements-dev.txt;

COPY . /code/

EXPOSE 8000

CMD ["bash", "./run.sh", "--dev"]
