services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: .
    command: >
      bash -c "python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8000

  nginx:
    image: nginx:1.22
    ports:
      - "443:443"
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/selfsigned.crt:/etc/nginx/selfsigned.crt
      - ./nginx/selfsigned.key:/etc/nginx/selfsigned.key      
    depends_on:
      - web
      
volumes:
  postgres_data:
  static_volume:
  media_volume:
