
* UI
- in admin timetable section:
  - add a link on the faculty to get to his profile,
- in admin/timetable/secsession:
  - make the section curriculum course and section faculty clicable,
  - add a filter for faculty (dropdown autocomplete
- in admin/timetable/semester:
  - make sure the count of students is done.  It should show the number of student having registered a course (completed or not) in this semester
- admin/timetable/acdemicyear:
  - add a columns, # of section  and # of student
- in eg admin/timetable/schedule/56/change/
  the list of section should indicate the semester

- in eg admin/timetable/semester/49/change/
  add an info field (yes it will change the DB but it is ok.)
- in eg admin/timetable/secsession/1644/change/
  add an info field (yes it will change the DB but it is ok.)

Registration status table is empty but it should be populated like other based status and type table at db initialisation. Check what is missing.

- in admin/registry/grade/
  - add a filter with student name or id (dropdown autocomplete) or make sure the search field expose name and studentid.
- in admin/people/student/
  - add a colum with culumative gpa
- in eg admin/people/student/6574/change/
  - organize the fied last school attended father name .. in to a bio section.
  - add a list of section enrolled with the grades if any for each section.
- investigate. opening a grade in admin/registry/grade/ -> eg admin/registry/grade/197582/change/ takes long (several seconds)    What is slowing down
- in  admin/people/faculty/310/change/
  - in the sections list, the semester does not need to be editable.
  - in the section list, each row should also indicate the number of enrolled students and the credit hours of the associated course
  - the section list should not be limited to current semester but list all section taught by the faculty

- Check that import_directory_people.py has been removed with pointing references.
- in admin/people/student
  - add a colum with latest enrolled_semester if know, and the cumulative gpa
  - in the filter, modify the label to make it clear how much credit is required for a student to be freshman sophomore ect.. in the filter eg freshman < 19 ch
  
- +check ScopedAutocompleteAdminMixin,+
* <2026-01-05 lun. 09:51> UI
- The bio field does not show in faculty

* <2026-01-05 lun. 07:33>  Runing a sql cmd
docker-compose -f docker-compose-preprod.yml exec -T db psql -U tusis_preprod -d tusis_preprod -c "SELECT version();"


* <2026-01-05 lun. 07:19>
- Make test for NameParts if I have empty parts.

* <2026-01-06 mar. 18:00> Notes on seed_full_student_grades.py
- Target reader: intermediate Python/pandas engineer; comfortable with typing, argparse, set ops.
- Typical US comp for that level: ~$110k–$150k base; higher with equity/bonus in SF/NYC/Seattle, closer to ~$100k–$120k in lower-cost areas.
- To increase abstraction difficulty: introduce pipeline composition/IoC for loaders+savers, plugin registry for scoring strategies, structured logging/metrics with failure policies, config-driven IO/validation, and immutable data models with strict mypy coverage.
