# Generated by Django 5.2 on 2025-12-18 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('finance', '0001_initial'),
        ('people', '0001_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.staff'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='semester',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='timetable.semester'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.student'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.staff'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default='pending', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.clearancestatus'),
        ),
        migrations.AddField(
            model_name='historicalscholarship',
            name='donor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.donor'),
        ),
        migrations.AddField(
            model_name='historicalscholarship',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalscholarship',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.student'),
        ),
        migrations.AddField(
            model_name='historicalsectionfee',
            name='fee_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default='other', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.feetype'),
        ),
        migrations.AddField(
            model_name='historicalsectionfee',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsectionfee',
            name='section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='timetable.section'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='curriculum_course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.curriculumcourse'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.staff'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.semester'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.student'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to='people.staff'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.clearancestatus'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(default='cash', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.paymentmethod'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, db_constraint=False, default='cash', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.paymentmethod'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='people.donor'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='people.student'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='scholarship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.scholarship'),
        ),
        migrations.AddField(
            model_name='historicalinvoice',
            name='scholarship',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.scholarship'),
        ),
        migrations.AddField(
            model_name='scholarshiplettertemplate',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_templates', to='people.donor'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='letter_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='finance.scholarshiplettertemplate'),
        ),
        migrations.AddField(
            model_name='historicalscholarship',
            name='letter_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.scholarshiplettertemplate'),
        ),
        migrations.AddField(
            model_name='scholarshiptermsnapshot',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_snapshots', to='timetable.semester'),
        ),
        migrations.AddField(
            model_name='scholarshiptermsnapshot',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_snapshots', to='people.student'),
        ),
        migrations.AddField(
            model_name='sectionfee',
            name='fee_type',
            field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.CASCADE, related_name='sections_fees', to='finance.feetype'),
        ),
        migrations.AddField(
            model_name='sectionfee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.section'),
        ),
        migrations.AlterUniqueTogether(
            name='scholarshiptermsnapshot',
            unique_together={('student', 'semester')},
        ),
    ]
