from django.db import transaction
from django.db.models import Max
from django.db.models.signals import pre_save
from django.dispatch import receiver

from app.timetable import Section


@receiver(pre_save, sender=Section)
def autoincrement_section_number(sender, instance, **kwargs):
    "to increment section number"
    # autoincrement_section_number() uses select_for_update(), which is good,
    # but you skip the logic when instance.pk is truthy. That is fine for
    # “update” operations, yet a bulk create with Section.objects.bulk_create()
    # will bypass the signal entirely.
    #  → Switch to a database GENERATED BY DEFAULT AS IDENTITY column or a
    # sequence so the DB enforces uniqueness, then expose it as number.
    # database-level CHECK constraints.
    if instance.pk or instance.number:

        return
    with transaction.atomic():
        last = (
            Section.objects.filter(course=instance.course, semester=instance.semester)
            .select_for_update()
            .aggregate(mx=Max("number"))
        )["mx"] or 0
        instance.number = last + 1
