TEST_PW = "test"

USER_ROLES: list[str] = [
    "student",
    "prospective_student",
    "dean",
    "chair",
    "lecturer",
    "assistant_professor",
    "associate_professor",
    "professor",
    "technician",
    "lab_technician",
    "faculty",
    "vpaa",
    "registrar",
    "financial_officer",
    "enrollment_officer",
]

DEFAULT_ROLE_TO_COLLEGE = {
    "dean": "COAS",  # map role → default college code
    "chair": "COAS",
    "lecturer": "COAS",
    "assistant_professor": "COAS",
    "associate_professor": "COAS",
    "professor": "COAS",
    "technician": "COAS",
    "lab_technician": "COAS",
    "faculty": "COAS",
}


MODEL_APP = {
    "reservation": "timetable",
    "college": "academics",
    "course": "academics",
    "curriculum": "academics",
    "concentration": "academics",
    "prerequisite": "academics",
    "curriculumcourse": "academics",
    "section": "timetable",
    "semester": "timetable",
    "term": "timetable",
    "academicyear": "timetable",
    "building": "spaces",
    "room": "spaces",
    "financialrecord": "finance",
    "paymenthistory": "finance",
    "profile": "people",
    "roleassignment": "people",
    "document": "registry",
    "registration": "registry",
    "classroster": "registry",
}

OBJECT_PERM_MATRIX = {
    "reservation": {
        "view": ["registrar", "enrollment_officer", "vpaa", "student"],
        "change": ["registrar", "enrollment_officer"],
        "delete": ["registrar"],
        "add": ["registrar", "enrollment_officer", "student"],
    },
    "prerequisite": {
        "view": ["dean", "chair", "registrar", "vpaa"],
        "add": ["dean", "registrar", "vpaa"],
        "change": ["dean", "registrar", "vpaa"],
        "delete": ["vpaa"],
    },
    "college": {
        "view": [
            "dean",
            "chair",
            "vpaa",
            "registrar",
            "student",
            "prospective_student",
        ],
        "change": ["dean", "vpaa"],
        "delete": ["vpaa"],
        "add": ["vpaa"],
    },
    "curriculum": {
        "view": [
            "dean",
            "chair",
            "faculty",
            "registrar",
            "vpaa",
            "student",
            "prospective_student",
        ],
        "change": ["dean", "registrar", "vpaa"],
        "delete": ["vpaa"],
        "add": ["dean", "registrar"],
    },
    "course": {
        "view": [
            "dean",
            "chair",
            "faculty",
            "lecturer",
            "registrar",
            "vpaa",
            "student",
            "prospective_student",
        ],
        "change": ["dean", "chair"],
        "delete": ["dean"],
        "add": ["chair", "dean"],
    },
    "section": {
        "view": [
            "dean",
            "chair",
            "faculty",
            "registrar",
            "vpaa",
            "lecturer",
            "student",
        ],
        "change": ["dean", "chair", "registrar"],
        "delete": ["registrar"],
        "add": ["registrar", "chair", "dean"],
    },
    "registration": {
        "view": ["registrar", "enrollment_officer", "vpaa", "student"],
        "change": ["registrar", "enrollment_officer"],
        "delete": ["registrar"],
        "add": ["registrar", "enrollment_officer", "student"],
    },
    "document": {
        "view": [
            "registrar",
            "financial_officer",
            "enrollment_officer",
            "student",
            "prospective_student",
        ],
        "change": ["registrar"],
        "delete": ["registrar"],
        "add": [
            "registrar",
            "enrollment_officer",
            "student",
            "prospective_student",
        ],
    },
    "financialrecord": {
        "view": ["financial_officer", "registrar", "student"],
        "change": ["financial_officer"],
        "delete": [],
        "add": ["financial_officer"],
    },
    "paymenthistory": {
        "view": ["financial_officer", "registrar", "student"],
        "change": ["financial_officer"],
        "delete": [],
        "add": ["financial_officer"],
    },
    "roleassignment": {
        "view": ["dean", "vpaa", "registrar"],
        "change": ["vpaa"],
        "delete": ["vpaa"],
        "add": ["vpaa"],
    },
    "room": {
        "view": [
            "dean",
            "chair",
            "registrar",
            "faculty",
            "student",
            "prospective_student",
        ],
        "change": ["registrar"],
        "delete": ["registrar"],
        "add": ["registrar"],
    },
    "building": {
        "view": [
            "registrar",
            "vpaa",
            "dean",
            "chair",
            "student",
            "prospective_student",
        ],
        "change": ["registrar"],
        "delete": ["vpaa"],
        "add": ["registrar", "vpaa"],
    },
    "academicyear": {
        "view": [
            "vpaa",
            "registrar",
            "dean",
            "chair",
            "student",
            "prospective_student",
        ],
        "change": ["vpaa"],
        "delete": ["vpaa"],
        "add": ["vpaa"],
    },
    "term": {
        "view": [
            "vpaa",
            "registrar",
            "dean",
            "chair",
            "student",
            "prospective_student",
        ],
        "change": ["vpaa", "registrar"],
        "delete": ["vpaa"],
        "add": ["registrar", "vpaa"],
    },
    "semester": {
        "view": [
            "vpaa",
            "registrar",
            "dean",
            "chair",
            "student",
            "prospective_student",
        ],
        "change": ["vpaa", "registrar"],
        "delete": ["vpaa"],
        "add": ["registrar", "vpaa"],
    },
}
