"""Build a read-only comprehensive source/pseudo-truth bundle."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TypeAlias

from app.shared.source_truth.curriculum_match import (
    apply_curriculum_matches_to_students,
    build_curriculum_match_map,
)
from app.shared.source_truth.conflicts import build_conflicts
from app.shared.source_truth.exports import (
    build_canonical_courses,
    build_canonical_curricula,
    build_canonical_curriculum_courses,
    write_import_ready_bundle,
)
from app.shared.source_truth.extractors import (
    load_fundamental_courses,
    load_fundamental_curricula,
    load_fundamental_curriculum_courses,
    load_grapro_courses,
    load_tucurricula_courses,
    load_tucurricula_curricula,
    load_tucurricula_curriculum_courses,
    load_tucurricula_requirements,
)
from app.shared.source_truth.fuzzy import (
    build_course_alias_candidates,
)
from app.shared.source_truth.fuzzy_students import build_student_identity_candidates
from app.shared.source_truth.inventory import (
    build_configured_inventory,
    build_smartschool_integrity,
    list_mdb_tables,
    ok_smartschool_tables,
)
from app.shared.source_truth.io import RowT, write_tsv
from app.shared.source_truth.records import (
    load_fundamental_students,
    load_grapro_students,
    load_passthrough_rows,
    load_smartschool_payments,
)
from app.shared.source_truth.smartschool_invalid import (
    load_invalid_smartschool_course_identities,
    load_repaired_smartschool_course_identities,
)
from app.shared.source_truth.smartschool_operational import (
    load_smartschool_course_registrations,
    load_smartschool_grades,
    load_smartschool_semester_enrollments,
)
from app.shared.source_truth.reports import report_specs, summary_text
from app.shared.source_truth.runbook import write_import_runbook
from app.shared.source_truth.scope import (
    FUNDAMENTAL_IMPORT_FILES,
    GRAPRO_IMPORT_FILES,
    SMARTSCHOOL_IMPORT_TABLES,
    TUCURRICULA_IMPORT_FILES,
)
from app.shared.source_truth.smartschool_catalog import (
    load_smartschool_courses,
    load_smartschool_curricula,
    load_smartschool_curriculum_courses,
)
from app.shared.source_truth.smartschool_students import load_smartschool_students
from app.shared.source_truth.staging import (
    open_stage,
    stage_output_count,
    stage_report_rows,
    stage_truth_witnesses,
)

RowsT: TypeAlias = list[RowT]
CountsT: TypeAlias = dict[str, int]


@dataclass(frozen=True)
class TruthBuildConfigT:
    """Configuration for one source-truth build run."""

    smartschool_dir: Path
    fundamentals_dir: Path
    grapro_csv_dir: Path
    grapro_mdb: Path
    tucurricula_import_dir: Path
    output_dir: Path


@dataclass(frozen=True)
class TruthBuildResultT:
    """Files and counts generated by the source-truth build."""

    output_dir: Path
    counts: CountsT


def default_output_dir() -> Path:
    """Return a timestamped ignored output path."""
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return Path("logs") / "tusis_truth" / stamp


def build_tusis_truth(config: TruthBuildConfigT) -> TruthBuildResultT:
    """Build the source-truth SQLite database and reviewable TSV reports."""
    config.output_dir.mkdir(parents=True, exist_ok=True)
    sqlite_path = config.output_dir / "truth.sqlite"
    _reset_sqlite_outputs(sqlite_path)
    conn = open_stage(sqlite_path)
    counts: CountsT = {}

    smartschool_integrity = build_smartschool_integrity(
        config.smartschool_dir, set(SMARTSCHOOL_IMPORT_TABLES)
    )
    ok_tables = ok_smartschool_tables(smartschool_integrity)
    inventory = build_configured_inventory(
        smartschool_dir=config.smartschool_dir,
        fundamentals_dir=config.fundamentals_dir,
        grapro_csv_dir=config.grapro_csv_dir,
        tucurricula_import_dir=config.tucurricula_import_dir,
        grapro_mdb=config.grapro_mdb,
        smartschool_tables=SMARTSCHOOL_IMPORT_TABLES,
        fundamental_files=FUNDAMENTAL_IMPORT_FILES,
        grapro_files=GRAPRO_IMPORT_FILES,
        tucurricula_files=TUCURRICULA_IMPORT_FILES,
    )
    mdb_tables = list_mdb_tables(config.grapro_mdb)
    invalid_course_identities = load_invalid_smartschool_course_identities(
        config.smartschool_dir, ok_tables
    )
    repaired_course_identities = load_repaired_smartschool_course_identities(
        config.smartschool_dir, ok_tables
    )

    tuc_courses = load_tucurricula_courses(config.tucurricula_import_dir)
    ss_courses = load_smartschool_courses(config.smartschool_dir, ok_tables)
    fund_courses = load_fundamental_courses(config.fundamentals_dir)
    gp_courses = load_grapro_courses(config.grapro_csv_dir)
    historical_courses = [*ss_courses, *fund_courses, *gp_courses]
    course_aliases = build_course_alias_candidates(historical_courses, tuc_courses)

    tuc_curricula = load_tucurricula_curricula(config.tucurricula_import_dir)
    ss_curricula = load_smartschool_curricula(config.smartschool_dir, ok_tables)
    fund_curricula = load_fundamental_curricula(config.fundamentals_dir)
    historical_curricula = [*ss_curricula, *fund_curricula]
    curriculum_matches, curriculum_aliases = build_curriculum_match_map(
        historical_curricula, tuc_curricula
    )

    tuc_curri_courses = load_tucurricula_curriculum_courses(config.tucurricula_import_dir)
    tuc_requirements = load_tucurricula_requirements(config.tucurricula_import_dir)
    ss_curri_courses = load_smartschool_curriculum_courses(
        config.smartschool_dir, ok_tables
    )
    fund_curri_courses = load_fundamental_curriculum_courses(config.fundamentals_dir)
    historical_curri_courses = [*ss_curri_courses, *fund_curri_courses]

    students = load_smartschool_students(config.smartschool_dir, ok_tables)
    if not students:
        students = load_fundamental_students(config.fundamentals_dir)
    students, student_curriculum_matches = apply_curriculum_matches_to_students(
        students, curriculum_matches
    )
    gp_students = load_grapro_students(config.grapro_csv_dir)
    student_matches = build_student_identity_candidates(students, gp_students)

    grades = load_smartschool_grades(config.smartschool_dir, ok_tables)
    if not grades:
        grades = load_passthrough_rows(
            config.fundamentals_dir / "full_grades.tsv", "fundamentals_smartschool"
        )
    registrations = load_smartschool_course_registrations(
        config.smartschool_dir, ok_tables
    )
    semester_enrollments = load_smartschool_semester_enrollments(
        config.smartschool_dir, ok_tables
    )
    if not semester_enrollments:
        semester_enrollments = load_passthrough_rows(
            config.fundamentals_dir / "registry_registration.csv",
            "fundamentals_smartschool",
        )
    payments = load_smartschool_payments(config.smartschool_dir, ok_tables)
    if not payments:
        payments = load_passthrough_rows(
            config.fundamentals_dir / "finance_payments.csv",
            "fundamentals_smartschool",
        )

    canonical_courses = build_canonical_courses(tuc_courses, historical_courses)
    canonical_curricula = build_canonical_curricula(tuc_curricula, historical_curricula)
    canonical_curri_courses = build_canonical_curriculum_courses(
        tuc_curri_courses, historical_curri_courses
    )
    conflicts = build_conflicts(
        smartschool_integrity,
        historical_courses,
        course_aliases,
        invalid_course_identities,
    )

    reports = report_specs(
        inventory=inventory,
        smartschool_integrity=smartschool_integrity,
        mdb_tables=mdb_tables,
        course_witnesses=[*tuc_courses, *historical_courses],
        course_aliases=course_aliases,
        invalid_course_identities=invalid_course_identities,
        repaired_course_identities=repaired_course_identities,
        curriculum_aliases=curriculum_aliases,
        student_matches=student_matches,
        student_curriculum_matches=student_curriculum_matches,
        canonical_courses=canonical_courses,
        canonical_curricula=canonical_curricula,
        canonical_curri_courses=canonical_curri_courses,
        conflicts=conflicts,
    )
    for filename, headers, rows in reports:
        counts[filename] = write_tsv(config.output_dir / filename, headers, rows)
        stage_report_rows(conn, filename, rows)
        stage_output_count(conn, filename, counts[filename])

    stage_truth_witnesses(
        conn,
        courses=[*tuc_courses, *historical_courses],
        curricula=[*tuc_curricula, *historical_curricula],
        curriculum_courses=[*tuc_curri_courses, *historical_curri_courses],
        requirements=tuc_requirements,
        students=[*students, *gp_students],
        grades=grades,
        registrations=registrations,
        semester_enrollments=semester_enrollments,
        payments=payments,
    )
    import_counts = write_import_ready_bundle(
        config.output_dir,
        courses=canonical_courses,
        curricula=canonical_curricula,
        curriculum_courses=canonical_curri_courses,
        requirements=tuc_requirements,
        students=students,
        grades=grades,
        registrations=registrations,
        semester_enrollments=semester_enrollments,
        payments=payments,
    )
    for filename, row_count in import_counts.items():
        counts[filename] = row_count
        stage_output_count(conn, filename, row_count)

    counts["IMPORT_RUNBOOK.org"] = write_import_runbook(
        config.output_dir,
        smartschool_dir=config.smartschool_dir,
    )
    (config.output_dir / "SUMMARY.txt").write_text(
        summary_text(config.output_dir, counts, smartschool_integrity),
        encoding="utf-8",
    )
    conn.close()
    return TruthBuildResultT(output_dir=config.output_dir, counts=counts)


def _reset_sqlite_outputs(sqlite_path: Path) -> None:
    """Remove stale generated SQLite files before rebuilding an output directory."""
    for path in (
        sqlite_path,
        sqlite_path.with_name(sqlite_path.name + "-wal"),
        sqlite_path.with_name(sqlite_path.name + "-shm"),
    ):
        if path.exists():
            path.unlink()
