# Generated by Django 5.2 on 2025-12-14 12:03

import app.people.utils
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDonor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("long_name", models.CharField(editable=False)),
                ("username", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("middle_name", models.CharField(blank=True)),
                ("name_prefix", models.CharField(blank=True, help_text="eg. 'Miss.'")),
                ("name_suffix", models.CharField(blank=True, help_text="eg. 'Phd.'")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                ("birth_place", models.CharField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("f", "Female"), ("m", "Male")]
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="A Liberian phone number",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        blank=True, help_text="eg. Tubman Town, Harper, Maryland"
                    ),
                ),
                ("father_address", models.CharField(blank=True)),
                ("father_name", models.CharField(blank=True)),
                ("nationality", models.CharField(blank=True)),
                (
                    "origin_county",
                    models.CharField(blank=True, help_text="eg. Maryland, Nigeria"),
                ),
                ("bio", models.TextField(blank=True)),
                ("photo", models.TextField(blank=True, max_length=100, null=True)),
                ("marital_status", models.CharField(blank=True)),
                (
                    "donor_id",
                    models.CharField(db_index=True, editable=False, max_length=13),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical donor",
                "verbose_name_plural": "historical donors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRoleAssignment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical role assignment",
                "verbose_name_plural": "historical role assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStaff",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("long_name", models.CharField(editable=False)),
                ("username", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("middle_name", models.CharField(blank=True)),
                ("name_prefix", models.CharField(blank=True, help_text="eg. 'Miss.'")),
                ("name_suffix", models.CharField(blank=True, help_text="eg. 'Phd.'")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                ("birth_place", models.CharField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("f", "Female"), ("m", "Male")]
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="A Liberian phone number",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        blank=True, help_text="eg. Tubman Town, Harper, Maryland"
                    ),
                ),
                ("father_address", models.CharField(blank=True)),
                ("father_name", models.CharField(blank=True)),
                ("nationality", models.CharField(blank=True)),
                (
                    "origin_county",
                    models.CharField(blank=True, help_text="eg. Maryland, Nigeria"),
                ),
                ("bio", models.TextField(blank=True)),
                ("photo", models.TextField(blank=True, max_length=100, null=True)),
                ("marital_status", models.CharField(blank=True)),
                (
                    "staff_id",
                    models.CharField(db_index=True, editable=False, max_length=13),
                ),
                ("employment_date", models.DateField(blank=True, null=True)),
                ("division", models.CharField(blank=True, max_length=100)),
                ("position", models.CharField(blank=True, max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical staff",
                "verbose_name_plural": "historical staffs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStudent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("long_name", models.CharField(editable=False)),
                ("username", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("middle_name", models.CharField(blank=True)),
                ("name_prefix", models.CharField(blank=True, help_text="eg. 'Miss.'")),
                ("name_suffix", models.CharField(blank=True, help_text="eg. 'Phd.'")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                ("birth_place", models.CharField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("f", "Female"), ("m", "Male")]
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="A Liberian phone number",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        blank=True, help_text="eg. Tubman Town, Harper, Maryland"
                    ),
                ),
                ("nationality", models.CharField(blank=True)),
                (
                    "origin_county",
                    models.CharField(blank=True, help_text="eg. Maryland, Nigeria"),
                ),
                ("bio", models.TextField(blank=True)),
                ("photo", models.TextField(blank=True, max_length=100, null=True)),
                ("marital_status", models.CharField(blank=True)),
                (
                    "student_id",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("last_school_attended", models.CharField(blank=True)),
                ("reason_for_leaving", models.CharField(blank=True)),
                ("father_name", models.CharField(blank=True)),
                ("father_address", models.CharField(blank=True)),
                ("mother_name", models.CharField(blank=True)),
                ("mother_address", models.CharField(blank=True)),
                ("emergency_contact", models.CharField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical student",
                "verbose_name_plural": "historical students",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_name", models.CharField(editable=False)),
                ("username", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("middle_name", models.CharField(blank=True)),
                ("name_prefix", models.CharField(blank=True, help_text="eg. 'Miss.'")),
                ("name_suffix", models.CharField(blank=True, help_text="eg. 'Phd.'")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                ("birth_place", models.CharField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("f", "Female"), ("m", "Male")]
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="A Liberian phone number",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        blank=True, help_text="eg. Tubman Town, Harper, Maryland"
                    ),
                ),
                ("father_address", models.CharField(blank=True)),
                ("father_name", models.CharField(blank=True)),
                ("nationality", models.CharField(blank=True)),
                (
                    "origin_county",
                    models.CharField(blank=True, help_text="eg. Maryland, Nigeria"),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=app.people.utils.photo_upload_to
                    ),
                ),
                ("marital_status", models.CharField(blank=True)),
                (
                    "staff_id",
                    models.CharField(editable=False, max_length=13, unique=True),
                ),
                ("employment_date", models.DateField(blank=True, null=True)),
                ("division", models.CharField(blank=True, max_length=100)),
                ("position", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_name", models.CharField(editable=False)),
                ("username", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("middle_name", models.CharField(blank=True)),
                ("name_prefix", models.CharField(blank=True, help_text="eg. 'Miss.'")),
                ("name_suffix", models.CharField(blank=True, help_text="eg. 'Phd.'")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                ("birth_place", models.CharField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("f", "Female"), ("m", "Male")]
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="A Liberian phone number",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        blank=True, help_text="eg. Tubman Town, Harper, Maryland"
                    ),
                ),
                ("nationality", models.CharField(blank=True)),
                (
                    "origin_county",
                    models.CharField(blank=True, help_text="eg. Maryland, Nigeria"),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=app.people.utils.photo_upload_to
                    ),
                ),
                ("marital_status", models.CharField(blank=True)),
                ("student_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("last_school_attended", models.CharField(blank=True)),
                ("reason_for_leaving", models.CharField(blank=True)),
                ("father_name", models.CharField(blank=True)),
                ("father_address", models.CharField(blank=True)),
                ("mother_name", models.CharField(blank=True)),
                ("mother_address", models.CharField(blank=True)),
                ("emergency_contact", models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_name", models.CharField(editable=False)),
                ("username", models.CharField()),
                ("email", models.EmailField(max_length=254)),
                ("middle_name", models.CharField(blank=True)),
                ("name_prefix", models.CharField(blank=True, help_text="eg. 'Miss.'")),
                ("name_suffix", models.CharField(blank=True, help_text="eg. 'Phd.'")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="date of birth"),
                ),
                ("birth_place", models.CharField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, choices=[("f", "Female"), ("m", "Male")]
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="A Liberian phone number",
                        max_length=128,
                        region=None,
                    ),
                ),
                (
                    "physical_address",
                    models.TextField(
                        blank=True, help_text="eg. Tubman Town, Harper, Maryland"
                    ),
                ),
                ("father_address", models.CharField(blank=True)),
                ("father_name", models.CharField(blank=True)),
                ("nationality", models.CharField(blank=True)),
                (
                    "origin_county",
                    models.CharField(blank=True, help_text="eg. Maryland, Nigeria"),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=app.people.utils.photo_upload_to
                    ),
                ),
                ("marital_status", models.CharField(blank=True)),
                (
                    "donor_id",
                    models.CharField(editable=False, max_length=13, unique=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        related_query_name="%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_profile", models.URLField(blank=True)),
                ("personal_website", models.URLField(blank=True)),
                ("academic_rank", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.college",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faculty",
                "verbose_name_plural": "Faculty profiles",
            },
        ),
        migrations.CreateModel(
            name="FacultyWorkloadSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_hours_assigned",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "credit_hours_delivered",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("overload_flag", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workload_snapshots",
                        to="people.faculty",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
    ]
