# Generated by Django 5.2 on 2025-05-24 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                ("email_number", models.CharField(blank=True, max_length=15)),
                ("enrollment_year", models.PositiveSmallIntegerField()),
                ("enrollment_date", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="student_photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "college",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.college",
                    ),
                ),
                (
                    "curriculum",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.curriculum",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("prospective_student", "Prospective Student"),
                            ("dean", "Dean"),
                            ("chair", "Chair"),
                            ("lecturer", "Lecturer"),
                            ("assistant_professor", "Assistant Professor"),
                            ("associate_professor", "Associate Professor"),
                            ("professor", "Professor"),
                            ("technician", "Technician"),
                            ("lab_technician", "Lab Technician"),
                            ("instructor", "Instructor"),
                            ("vpaa", "Vpaa"),
                            ("registrar", "Registrar"),
                            ("financial_officer", "Financial Officer"),
                            ("enrollment_officer", "Enrollment Officer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments",
                        to="academics.college",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["role", "college", "end_date"],
                        name="people_role_role_967f94_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role", "college", "start_date"),
                        name="unique_role_per_period",
                    )
                ],
            },
        ),
    ]
