# Generated by Django 5.2 on 2025-05-24 19:14

from django.db import migrations
import datetime


def populate_enrollment_date(apps, schema_editor):
    StudentProfile = apps.get_model("people", "StudentProfile")
    for profile in StudentProfile.objects.filter(enrollment_date__isnull=True):
        if profile.enrollment_year:
            profile.enrollment_date = datetime.date(profile.enrollment_year, 1, 1)
            profile.save(update_fields=["enrollment_date"])


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_enrollment_date, migrations.RunPython.noop)
    ]
