# Generated by Django 5.2 on 2025-08-16 11:55

import datetime
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def seed_credit_hours(apps, schema_editor):
    CreditHour = apps.get_model("academics", "CreditHour")
    entries = [(n, str(n)) for n in range(0, 11)] + [(99, "99")]
    CreditHour.objects.bulk_create(
        [CreditHour(code=code, label=label) for code, label in entries]
    )


def seed_curriculum_statuses(apps, schema_editor):
    CurriculumStatus = apps.get_model("academics", "CurriculumStatus")
    entries = [
        ("pending", "Pending"),
        ("approved", "Approved"),
        ("needs_revision", "Needs Revision"),
    ]
    CurriculumStatus.objects.bulk_create(
        [CurriculumStatus(code=code, label=label) for code, label in entries]
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditHour',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumStatus',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_credit_hours),
        migrations.RunPython(seed_curriculum_statuses),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='deft')),
                ('long_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_college_code'), models.UniqueConstraint(fields=('long_name',), name='unique_college_name')],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=40)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=False)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='academics.college')),
                ('status', models.ForeignKey(default='pending', on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academics.curriculumstatus', verbose_name='Validation Status')),
            ],
            options={
                'ordering': ['college', 'short_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=6)),
                ('long_name', models.CharField(blank=True, max_length=128)),
                ('code', models.CharField(editable=False, max_length=50, unique=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='academics.college')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('code', models.CharField(editable=False, max_length=20)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCollege',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(default='deft')),
                ('long_name', models.CharField(blank=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical college',
                'verbose_name_plural': 'historical colleges',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCourse',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('code', models.CharField(editable=False, max_length=20)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical course',
                'verbose_name_plural': 'historical courses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCurriculum',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('short_name', models.CharField(max_length=40)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=False)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('college', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.college')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, db_constraint=False, default='pending', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.curriculumstatus', verbose_name='Validation Status')),
            ],
            options={
                'verbose_name': 'historical curriculum',
                'verbose_name_plural': 'historical curriculums',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDepartment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('short_name', models.CharField(max_length=6)),
                ('long_name', models.CharField(blank=True, max_length=128)),
                ('code', models.CharField(db_index=True, editable=False, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('college', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.college')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical department',
                'verbose_name_plural': 'historical departments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrerequisite',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.course')),
                ('curriculum', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.curriculum')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prerequisite_course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.course')),
            ],
            options={
                'verbose_name': 'historical prerequisite',
                'verbose_name_plural': 'historical prerequisites',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProgram',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('is_elective', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('course', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.course')),
                ('credit_hours', models.ForeignKey(blank=True, db_constraint=False, default=3, help_text='Credits to be used in this curriculum for this course', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.credithour')),
                ('curriculum', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.curriculum')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical program',
                'verbose_name_plural': 'historical programs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_credit_hours', models.PositiveIntegerField(default=50)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.curriculum')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_credit_hours', models.PositiveIntegerField(default=20)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.curriculum')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prereq_edges', to='academics.course')),
                ('curriculum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='academics.curriculum')),
                ('prerequisite_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_edges', to='academics.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_courses', through='academics.Prerequisite', to='academics.course'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('is_elective', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_programs', to='academics.course')),
                ('credit_hours', models.ForeignKey(default=3, help_text='Credits to be used in this curriculum for this course', on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='academics.credithour')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.curriculum')),
            ],
            options={
                'ordering': ['curriculum'],
            },
        ),
        migrations.CreateModel(
            name='MinorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.minor')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
            ],
        ),
        migrations.AddField(
            model_name='minor',
            name='programs',
            field=models.ManyToManyField(related_name='minors', through='academics.MinorProgram', to='academics.program'),
        ),
        migrations.CreateModel(
            name='MajorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.major')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
            ],
        ),
        migrations.AddField(
            model_name='major',
            name='programs',
            field=models.ManyToManyField(related_name='majors', through='academics.MajorProgram', to='academics.program'),
        ),
        migrations.CreateModel(
            name='HistoricalMinorProgram',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('minor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.minor')),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.program')),
            ],
            options={
                'verbose_name': 'historical minor program',
                'verbose_name_plural': 'historical minor programs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMajorProgram',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('major', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.major')),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.program')),
            ],
            options={
                'verbose_name': 'historical major program',
                'verbose_name_plural': 'historical major programs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='curricula', through='academics.Program', to='academics.course'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('short_name', 'college'), name='uniq_department_short_name_per_college'),
        ),
        migrations.AddConstraint(
            model_name='prerequisite',
            constraint=models.UniqueConstraint(fields=('curriculum', 'course', 'prerequisite_course'), name='uniq_prerequisite_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='prerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('course', models.F('prerequisite_course')), _negated=True), name='no_self_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('department', 'number'), name='uniq_course_number_per_department'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('curriculum', 'course'), name='uniq_course_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='minorprogram',
            constraint=models.UniqueConstraint(fields=('minor', 'program'), name='uniq_program_per_minor'),
        ),
        migrations.AddConstraint(
            model_name='majorprogram',
            constraint=models.UniqueConstraint(fields=('major', 'program'), name='uniq_program_per_major'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('college', 'short_name'), name='uniq_active_curriculum_college'),
        ),
    ]
