# Generated by Django 5.2 on 2025-11-30 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcourse',
            name='credit_hours',
            field=models.ForeignKey(default=3, help_text='Credits to be used in this curriculum for this course', on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_courses', to='shared.credithour'),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='curriculum_course',
            field=models.ManyToManyField(blank=True, related_name='curricula', through='academics.CurriculumCourse', to='academics.course'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='status',
            field=models.ForeignKey(default='pending', on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academics.curriculumstatus', verbose_name='Validation Status'),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='academics.college'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.department'),
        ),
        migrations.AddField(
            model_name='historicalcollege',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.department'),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcurriculum',
            name='college',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.college'),
        ),
        migrations.AddField(
            model_name='historicalcurriculum',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcurriculum',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, default='pending', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.curriculumstatus', verbose_name='Validation Status'),
        ),
        migrations.AddField(
            model_name='historicalcurriculumcourse',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.course'),
        ),
        migrations.AddField(
            model_name='historicalcurriculumcourse',
            name='credit_hours',
            field=models.ForeignKey(blank=True, db_constraint=False, default=3, help_text='Credits to be used in this curriculum for this course', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shared.credithour'),
        ),
        migrations.AddField(
            model_name='historicalcurriculumcourse',
            name='curriculum',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='historicalcurriculumcourse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='college',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.college'),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmajorcurriculumcourse',
            name='curriculum_course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.curriculumcourse'),
        ),
        migrations.AddField(
            model_name='historicalmajorcurriculumcourse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalminorcurriculumcourse',
            name='curriculum_course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.curriculumcourse'),
        ),
        migrations.AddField(
            model_name='historicalminorcurriculumcourse',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprerequisite',
            name='course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.course'),
        ),
        migrations.AddField(
            model_name='historicalprerequisite',
            name='curriculum',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='historicalprerequisite',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprerequisite',
            name='prerequisite_course',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.course'),
        ),
        migrations.AddField(
            model_name='major',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='historicalmajorcurriculumcourse',
            name='major',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.major'),
        ),
        migrations.AddField(
            model_name='majorcurriculumcourse',
            name='curriculum_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_link', to='academics.curriculumcourse'),
        ),
        migrations.AddField(
            model_name='majorcurriculumcourse',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.major'),
        ),
        migrations.AddField(
            model_name='major',
            name='curriculum_courses',
            field=models.ManyToManyField(related_name='majors', through='academics.MajorCurriculumCourse', to='academics.curriculumcourse'),
        ),
        migrations.AddField(
            model_name='minor',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='historicalminorcurriculumcourse',
            name='minor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.minor'),
        ),
        migrations.AddField(
            model_name='minorcurriculumcourse',
            name='curriculum_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minor_links', to='academics.curriculumcourse'),
        ),
        migrations.AddField(
            model_name='minorcurriculumcourse',
            name='minor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.minor'),
        ),
        migrations.AddField(
            model_name='minor',
            name='curriculum_courses',
            field=models.ManyToManyField(related_name='minors', through='academics.MinorCurriculumCourse', to='academics.curriculumcourse'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prereq_edges', to='academics.course'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='academics.curriculum'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='prerequisite_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for_edges', to='academics.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_courses', through='academics.Prerequisite', to='academics.course'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.UniqueConstraint(fields=('curriculum', 'course'), name='uniq_course_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('short_name',), name='uniq_active_curriculum_college'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('short_name', 'college'), name='uniq_department_short_name_per_college'),
        ),
        migrations.AddConstraint(
            model_name='majorcurriculumcourse',
            constraint=models.UniqueConstraint(fields=('major', 'curriculum_course'), name='uniq_curriculum_course_per_major'),
        ),
        migrations.AddConstraint(
            model_name='minorcurriculumcourse',
            constraint=models.UniqueConstraint(fields=('minor', 'curriculum_course'), name='uniq_curriculum_course_per_minor'),
        ),
        migrations.AddConstraint(
            model_name='prerequisite',
            constraint=models.UniqueConstraint(fields=('curriculum', 'course', 'prerequisite_course'), name='uniq_prerequisite_per_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='prerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('course', models.F('prerequisite_course')), _negated=True), name='no_self_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('department', 'code', 'number'), name='uniq_course_codenumber_per_department'),
        ),
    ]
