# Generated by Django 5.2 on 2025-12-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculum",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalcurriculum",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="major",
            name="info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="minor",
            name="info",
            field=models.TextField(blank=True),
        ),
    ]
