# Generated by Django 5.2 on 2025-12-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["code"]},
        ),
    ]
