# Generated by Django 5.2 on 2025-12-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_curriculum_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="major",
            name="info",
        ),
        migrations.RemoveField(
            model_name="minor",
            name="info",
        ),
    ]
