# Generated by Django 5.2 on 2025-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_remove_major_info_remove_minor_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ["college__code", "code"]},
        ),
        migrations.RemoveConstraint(
            model_name="department",
            name="uniq_department_short_name_per_college",
        ),
        migrations.RemoveField(
            model_name="department",
            name="short_name",
        ),
        migrations.RemoveField(
            model_name="historicaldepartment",
            name="short_name",
        ),
        migrations.AddField(
            model_name="department",
            name="shortname",
            field=models.CharField(
                default="(DFT) DFT", editable=False, max_length=50, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="shortname",
            field=models.CharField(
                db_index=True, default="DFT", editable=False, max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="historicaldepartment",
            name="code",
            field=models.CharField(max_length=8),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("code", "college"), name="uniq_department_code_per_college"
            ),
        ),
    ]
