#+TITLE: Transcript - 31625
#+AUTHOR: Office of the Registrar
#+DATE: June 20, 2026
#+LATEX_CLASS: tutranscript
#+LATEX_CLASS_OPTIONS: [10pt,a4paper]
#+LATEX_COMPILER: lualatex
#+OPTIONS: toc:nil title:nil author:nil date:nil ^:nil
#+EXPORT_FILE_NAME: transcript

#+LATEX_HEADER: \renewcommand{\TUTranscriptLogoFile}{logo120pi.png}
#+LATEX_HEADER: \renewcommand{\TUTranscriptInstitutionName}{William V.S. Tubman University}
#+LATEX_HEADER: \renewcommand{\TUTranscriptAddressOne}{Tubman Town, East Harper}
#+LATEX_HEADER: \renewcommand{\TUTranscriptAddressTwo}{Maryland County}
#+LATEX_HEADER: \renewcommand{\TUTranscriptCountry}{Republic of Liberia}
#+LATEX_HEADER: \renewcommand{\TUTranscriptWebsite}{www.Tubmanu.edu.lr}
#+LATEX_HEADER: \renewcommand{\TUTranscriptRegistrarEmail}{registrar@tubmanu.edu.lr}
#+LATEX_HEADER: \renewcommand{\TUTranscriptDocumentTitle}{Official Student Transcript}
#+LATEX_HEADER: \renewcommand{\TUTranscriptDraftLabel}{}
#+LATEX_HEADER: \renewcommand{\TUTranscriptStudentName}{Anthony Klakur Tchouin}
#+LATEX_HEADER: \renewcommand{\TUTranscriptStudentAddressOne}{Hoffman Station, Harper City, Maryland County, Liberi,}
#+LATEX_HEADER: \renewcommand{\TUTranscriptStudentAddressTwo}{}
#+LATEX_HEADER: \renewcommand{\TUTranscriptStudentID}{31625}
#+LATEX_HEADER: \renewcommand{\TUTranscriptDOB}{May 17, 1982}
#+LATEX_HEADER: \renewcommand{\TUTranscriptCollege}{Default College}
#+LATEX_HEADER: \renewcommand{\TUTranscriptProgramCode}{DFT\_CUR}
#+LATEX_HEADER: \renewcommand{\TUTranscriptProgramName}{Default Curriculum}
#+LATEX_HEADER: \renewcommand{\TUTranscriptMajorProgram}{Default Curriculum}
#+LATEX_HEADER: \renewcommand{\TUTranscriptEnrollmentDate}{N/A}
#+LATEX_HEADER: \renewcommand{\TUTranscriptCompletionDate}{N/A}
#+LATEX_HEADER: \renewcommand{\TUTranscriptGraduationDate}{N/A}
#+LATEX_HEADER: \renewcommand{\TUTranscriptProgramTotalAttempted}{144}
#+LATEX_HEADER: \renewcommand{\TUTranscriptProgramTotalEarned}{144}
#+LATEX_HEADER: \renewcommand{\TUTranscriptProgramTotalGPA}{3.26}
#+LATEX_HEADER: \renewcommand{\TUTranscriptCumulativeTotalAttempted}{144}
#+LATEX_HEADER: \renewcommand{\TUTranscriptCumulativeTotalEarned}{144}
#+LATEX_HEADER: \renewcommand{\TUTranscriptCumulativeTotalGPA}{3.26}
#+LATEX_HEADER: \renewcommand{\TUTranscriptPrintedDate}{June 20, 2026}
#+LATEX_HEADER: \renewcommand{\TUTranscriptPrintedDateShort}{20-Jun-2026}
#+LATEX_HEADER: \renewcommand{\TUTranscriptGradeLegend}{A = 90-100; B = 80-89; C = 70-79; D = 60-69; F = Below 60}
#+LATEX_HEADER: \renewcommand{\TUTranscriptGradePolicyIntro}{Each course is assigned credit in semester hours. One semester hour is defined as fifty (50) contact minutes and, where applicable, three hours per week of practical or laboratory work throughout a fifteen-week semester.}
#+LATEX_HEADER: \renewcommand{\TUTranscriptMentionRulesNote}{Mention and honor thresholds are to be confirmed by the Registrar before final transcript publication.}
#+LATEX_HEADER: \renewcommand{\TUTranscriptNoticeFinal}{This is a true copy of the records for the above named student. When inscribed with the seal of William V.S. Tubman University Registrar's Office, this constitutes an Official Transcript.}
#+LATEX_HEADER: \renewcommand{\TUTranscriptRegistrarTitle}{REGISTRAR}

* Transcript Source
This source is intended for export with the bundled tutranscript class.

#+begin_export latex
\renewcommand{\TUTranscriptDetailRows}{%
  \TUTranscriptProgramRow{DFT\_CUR}{Default Curriculum}
  \TUTranscriptTermHeader{2022-2023, 1st Semester}
  \TUTranscriptCourse{BIOL101}{General Biology I}{B}{4}{4}{12}
  \TUTranscriptCourse{ENGL101}{English Grammar and Phonetics}{C}{3}{3}{6}
  \TUTranscriptCourse{HIST201}{Liberian History and Society}{B}{3}{3}{9}
  \TUTranscriptCourse{MATH101}{College Algebra}{B}{3}{3}{9}
  \TUTranscriptCourse{PSY101}{Introduction to Psychology}{B}{3}{3}{9}
  \TUTranscriptTotals{Term Totals}{2.81}{16}{16}{45}
  \TUTranscriptTotals{Program Totals}{2.81}{16}{16}{45}
  \TUTranscriptTermHeader{2022-2023, 2nd Semester}
  \TUTranscriptCourse{CHEM101}{Principles of Chemistry}{C}{4}{4}{8}
  \TUTranscriptCourse{ENGL102}{Academic Reading and Writing}{C}{3}{3}{6}
  \TUTranscriptCourse{MATH102}{Geometry and Trigonometry}{A}{3}{3}{12}
  \TUTranscriptCourse{PHIL101}{Introduction to Philosophy}{B}{3}{3}{9}
  \TUTranscriptTotals{Term Totals}{2.69}{13}{13}{35}
  \TUTranscriptTotals{Program Totals}{2.76}{29}{29}{80}
  \TUTranscriptTermHeader{2023-2024, 1st Semester}
  \TUTranscriptCourse{EDU250}{Peace Education}{B}{3}{3}{9}
  \TUTranscriptCourse{EDU251}{Introduction to Teaching Field Experience}{B}{3}{3}{9}
  \TUTranscriptCourse{ENGL201}{Technical Communication}{C}{3}{3}{6}
  \TUTranscriptCourse{ENVS201}{Introduction to Environmental Science}{C}{3}{3}{6}
  \TUTranscriptCourse{FREN201}{Introduction to French}{A}{3}{3}{12}
  \TUTranscriptCourse{PE101}{Fitness and Wellness I}{B}{1}{1}{3}
  \TUTranscriptTotals{Term Totals}{2.81}{16}{16}{45}
  \TUTranscriptTotals{Program Totals}{2.78}{45}{45}{125}
  \TUTranscriptTermHeader{2023-2024, 2nd Semester}
  \TUTranscriptCourse{EDU252}{The Social World of the Child and Adolescent}{B}{3}{3}{9}
  \TUTranscriptCourse{EDU254}{Speech, Language and Learning}{B}{3}{3}{9}
  \TUTranscriptCourse{ENGL204}{Introduction to Literature}{C}{3}{3}{6}
  \TUTranscriptCourse{FREN202}{Intermediate French}{B}{3}{3}{9}
  \TUTranscriptCourse{HIST202}{World History}{A}{3}{3}{12}
  \TUTranscriptTotals{Term Totals}{3.00}{15}{15}{45}
  \TUTranscriptTotals{Program Totals}{2.83}{60}{60}{170}
  \TUTranscriptTermHeader{2023-2024, Vac School}
  \TUTranscriptCourse{CSE101}{Introduction to Computers}{B}{3}{3}{9}
  \TUTranscriptCourse{EDU258}{Principles and Foundation of Education}{C}{3}{3}{6}
  \TUTranscriptCourse{PE102}{Fitness and Wellness II}{B}{1}{1}{3}
  \TUTranscriptTotals{Term Totals}{2.57}{7}{7}{18}
  \TUTranscriptTotals{Program Totals}{2.81}{67}{67}{188}
  \TUTranscriptTermHeader{2024-2025, 1st Semester}
  \TUTranscriptCourse{EDU351}{Diagnosing and Assessing Learning}{B}{3}{3}{9}
  \TUTranscriptCourse{EDU353}{Culture, Cognition and Learning}{B}{3}{3}{9}
  \TUTranscriptCourse{EDU355}{Understanding Students with Exceptionalites}{B}{3}{3}{9}
  \TUTranscriptCourse{EEDU301}{Enterpreneurship Education-I}{A}{0}{0}{0}
  \TUTranscriptCourse{HIST372}{Africa and the Trans-Atlantic Slave Trade}{A}{3}{3}{12}
  \TUTranscriptCourse{HIST373}{European History I: The Middle Ages to the 14th Century}{A}{3}{3}{12}
  \TUTranscriptTotals{Term Totals}{3.40}{15}{15}{51}
  \TUTranscriptTotals{Program Totals}{2.91}{82}{82}{239}
  \TUTranscriptTermHeader{2024-2025, 2nd Semester}
  \TUTranscriptCourse{EDU350}{Ethnographic Studies in Rural Communities}{A}{3}{3}{12}
  \TUTranscriptCourse{EDU354}{Classroom Management:Designing \& Managing the Learning Environment}{A}{3}{3}{12}
  \TUTranscriptCourse{EDU384}{Method of Teaching History}{A}{3}{3}{12}
  \TUTranscriptCourse{ENGL378}{Gender, Feminism and Contemporary Literature}{A}{3}{3}{12}
  \TUTranscriptCourse{HIST374}{European History II: The Renaissance to the Emergence of the Modern European States}{B}{3}{3}{9}
  \TUTranscriptCourse{HIST378}{African Film, Arts and Politics}{B}{3}{3}{9}
  \TUTranscriptTotals{Term Totals}{3.67}{18}{18}{66}
  \TUTranscriptTotals{Program Totals}{3.05}{100}{100}{305}
  \TUTranscriptTermHeader{2024-2025, Vac School}
  \TUTranscriptCourse{EDU256}{School Pedagogy and Social Justice}{A}{3}{3}{12}
  \TUTranscriptCourse{EDU358}{Educational Administration}{B}{3}{3}{9}
  \TUTranscriptCourse{EDU471}{Literacy Instructions in Content Areas in Jr. and Sr. High Schools}{A}{3}{3}{12}
  \TUTranscriptTotals{Term Totals}{3.67}{9}{9}{33}
  \TUTranscriptTotals{Program Totals}{3.10}{109}{109}{338}
  \TUTranscriptTermHeader{2025-2026, 1st Semester}
  \TUTranscriptCourse{EDU357}{Geography in the Social Studies Curriculum (Elem. and Jr. High)}{A}{3}{3}{12}
  \TUTranscriptCourse{EDU455}{Educational Research Methodology I}{A}{3}{3}{12}
  \TUTranscriptCourse{EDU475}{Curriculum and Instruction Student Teaching I}{A}{3}{3}{12}
  \TUTranscriptCourse{EDU477}{Curriculum Instruction Teaching, seminar I}{A}{1}{1}{4}
  \TUTranscriptCourse{HIST371}{Pre-Colonial Africa}{A}{3}{3}{12}
  \TUTranscriptCourse{HIST471}{Contemporary History of Liberia}{B}{3}{3}{9}
  \TUTranscriptTotals{Term Totals}{3.81}{16}{16}{61}
  \TUTranscriptTotals{Program Totals}{3.19}{125}{125}{399}
  \TUTranscriptTermHeader{2025-2026, 2nd Semester}
  \TUTranscriptCourse{CSE102}{Computer Literacy}{B}{3}{3}{9}
  \TUTranscriptCourse{EDU458}{Advocacy, Networking and Collaboration in School and Community}{B}{3}{3}{9}
  \TUTranscriptCourse{EDU476}{Curriculum and Instruction Student Teaching II}{A}{3}{3}{12}
  \TUTranscriptCourse{EDU478}{Seminar II}{A}{1}{1}{4}
  \TUTranscriptCourse{EEDU302}{Enterpreneurship Education-II}{B}{0}{0}{0}
  \TUTranscriptCourse{HIST376}{Post Colonial Africa}{A}{3}{3}{12}
  \TUTranscriptCourse{HIST472}{Urbanization of Contemporary Africa: Space, Identity and Politics}{A}{3}{3}{12}
  \TUTranscriptCourse{HIST475}{Running While others Walk}{A}{3}{3}{12}
  \TUTranscriptTotals{Term Totals}{3.68}{19}{19}{70}
  \TUTranscriptTotals{Program Totals}{3.26}{144}{144}{469}
}
\TUPrintTranscript
#+end_export
