"""Column name mappings for import resources."""

# Incoming headers -> canonical column names used by FacultyResource
FACULTY_COLUMN_MAP = {
    "Instructor": "faculty",
    "name_prefix": "name_prefix",
    "first_n": "first_name",
    "middle_n": "middle_name",
    "last_n": "last_name",
    "name_suffix": "name_suffix",
    "username": "username",
}

STUDENT_HEADER_MAP = {
    "AcademicYear": "academic_year",
    # "AccountID": "AccountID",
    "AdmissionStatus": "bio_admissionstatus",
    # "Amt": "Amt",
    # "ClassLevel": "ClassLevel",
    "ConfidentialInfoFlag": "bio_confidentialinfoflag",
    "CountyOfOrigin": "origin_county",
    # "CourseCode": "CourseCode",
    # "CourseNo": "CourseNo",
    # "CreditHours": "CreditHours",
    # "CumAttemptedHours": "CumAttemptedHours",
    # "CumAttemptedHoursLocal": "CumAttemptedHoursLocal",
    # "CumEarnedHours": "CumEarnedHours",
    # "CumEarnedHoursLocal": "CumEarnedHoursLocal",
    # "CumGPA": "CumGPA",
    # "CumGPALocal": "CumGPALocal",
    # "CumQualityHours": "CumQualityHours",
    # "CumQualityHoursLocal": "CumQualityHoursLocal",
    # "CumQualityPoints": "CumQualityPoints",
    # "CumQualityPointsLocal": "CumQualityPointsLocal",
    # "CumRetainedHours": "CumRetainedHours",
    # "CumRetainedHoursLocal": "CumRetainedHoursLocal",
    # "Curr": "Curr",
    "DateOfBirth": "birth_date",
    # "DisableWebConnectPortal": "DisableWebConnectPortal",
    "EmergencyContact": "emergency_contact",
    "Enrolled": "bio_Enrolled",
    "EnrollmentStatusID": "bio_EnrollmentStatusID",
    "EnrollmentType": "bio_EnrollmentType",
    "FatherAddress": "father_address",
    "FatherName": "father_name",
    "HomeCountry": "bio_homecountry",  
    "LastSchoolAttended": "last_school_attended",
    "LastSchoolType": "bio_lastschooltype",
    "MotherAddress": "mother_address",
    "MotherName": "mother_name",
    "Nationality": "nationality",
    "NumDependents": "bio_numdependents",
    # "PENVerified": "PENVerified",
    "PlaceOfBirth": "birth_place",
    # "ProgramID": "ProgramID",
    "Scholarship": "bio_scholarship",
    # "Section": "Section",
    # "Semester": "Semester",
    "StudentID": "Student_id",
    "TermFirstEntered": "bio_termfirstentered", 
    # "TermLastEnrolled": "bio_termlastenrooled",
    "TimeCreated": "bio_timecreated",
    # "TimeModified": "TimeModified",
    # "Uploaded": "Uploaded",
    "VeteranStatusID": "bio_veteranstatusid",
    # "Withdrew": "Withdrew",
    "YearOfEntry": "entry_year",
    "address": "physical_address",
    "college_code": "college_code",  # needed for the curriculum
    "curriculum_short_name": "curriculum_short_name",  # needed for the curriculum
    "enrollement_semester": "entry_semester",
    "first_name": "first_name",
    "gender": "gender",
    "last_name": "last_name",
    "marital_status": "marital_status",
    "middle_name": "middle_name",
    "personal_email": "personal_email",
    "phone_no": "phone_number",
}
