"""Column name mappings for import resources."""

# Incoming headers -> canonical column names used by FacultyResource
FACULTY_COLUMN_MAP = {
    "Instructor": "faculty",
    "name_prefix": "name_prefix",
    "first_n": "first_name",
    "middle_n": "middle_name",
    "last_n": "last_name",
    "name_suffix": "name_suffix",
    "username": "username",
}

STUDENT_HEADER_MAP = {
    "Student": "student_name",
    "Dept": "department",
    "curriculum": "curriculum",
    "StudentID": "student_id",
    "DOB": "birth_date",
    "Mobile": "phone_no",
}
GENDER_MAP = {
    "M": "m",  # should use lower
    "F": "f",    # should use lower
    "male": "m",
    "m": "m",
    "female": "f",
    "f": "f",
}

STUDENT_HEADER_MAP = {
    "AcademicYear": "academic_year",
    "AccountID": "student_id",  # > ! this key is only from studeninfo
    "AdmissionStatus": "bio_admissionstatus",
    "ConfidentialInfoFlag": "bio_confidentialinfoflag",
    "CountyOfOrigin": "origin_county",
    "DateOfBirth": "birth_date",
    "EmergencyContact": "emergency_contact",
    "Enrolled": "bio_Enrolled",
    "EnrollmentStatusID": "bio_EnrollmentStatusID",
    "EnrollmentType": "bio_EnrollmentType",
    "FatherAddress": "father_address",
    "FatherName": "father_name",
    "HomeCountry": "bio_homecountry",  
    "LastSchoolAttended": "last_school_attended",
    "LastSchoolType": "bio_lastschooltype",
    "MotherAddress": "mother_address",
    "MotherName": "mother_name",
    "Nationality": "nationality",
    "NumDependents": "bio_numdependents",
    "PlaceOfBirth": "birth_place",
    "Scholarship": "bio_scholarship",
    "Section": "section_no",
    "Semester": "semester_no",
    "StudentID": "student_id",
    "TermFirstEntered": "bio_termfirstentered", 
    "TimeCreated": "bio_timecreated",
    "VeteranStatusID": "bio_veteranstatusid",
    "YearOfEntry": "entry_year",
    "address": "physical_address",
    "enrollement_semester": "entry_semester",
    # "Amt": "Amt",
    # "ClassLevel": "ClassLevel",
    # "CourseCode": "CourseCode",
    # "CourseNo": "CourseNo",
    # "CreditHours": "CreditHours",
    # "CumAttemptedHours": "CumAttemptedHours",
    # "CumAttemptedHoursLocal": "CumAttemptedHoursLocal",
    # "CumEarnedHours": "CumEarnedHours",
    # "CumEarnedHoursLocal": "CumEarnedHoursLocal",
    # "CumGPA": "CumGPA",
    # "CumGPALocal": "CumGPALocal",
    # "CumQualityHours": "CumQualityHours",
    # "CumQualityHoursLocal": "CumQualityHoursLocal",
    # "CumQualityPoints": "CumQualityPoints",
    # "CumQualityPointsLocal": "CumQualityPointsLocal",
    # "CumRetainedHours": "CumRetainedHours",
    # "CumRetainedHoursLocal": "CumRetainedHoursLocal",
    # "Curr": "Curr",
    # "DisableWebConnectPortal": "DisableWebConnectPortal",
    # "PENVerified": "PENVerified",
    # "ProgramID": "ProgramID",
    # "TermLastEnrolled": "bio_termlastenrooled",
    # "TimeModified": "TimeModified",
    # "Uploaded": "Uploaded",
    # "Withdrew": "Withdrew",
}
